pip install django
pip install django-bootstrap4
pip install social-auth-app-django
pip install pillow
pip install easy-thumbnails
pip install django-cleanup
pip install django-simple-captcha
pip install djangorestframework
pip install django-cors-headers
